export const dummyData = [
  {
    id: 1,
    img: "product1",
    name: "Смартфон Samsung Galaxy",
    price: "7 300 000",
    text: "Euismod faucibus turpis eu gravida mi. Pellentesque et velit aliquam .",
    discount: true,
    prize: true,
    refresh: false,
  },
  {
    id: 2,
    img: "product2",
    name: "Смартфон Apple iphone",
    price: "7 300 000",
    text: "Pellentesque et velit aliqua. Euismod faucibus turpis eu gravida mi .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 3,
    img: "product3",
    name: "Наушники Apple Airpods Pro",
    price: "7 300 000",
    text: "Gravida mi euismod faucibus turpis eu . Pellentesque et velit aliquam .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 4,
    img: "product4",
    name: "Samsung Galaxy Z Fold Plus",
    price: "7 300 000",
    text: "Aliquam euismod faucibus turpis eu gravida mi. Pellentesque et velit .",
    discount: true,
    prize: true,
    refresh: false,
  },
  {
    id: 5,
    img: "product5",
    name: "Смартфон Apple iphone",
    price: "7 300 000",
    text: "Aliquam euismod faucibus turpis eu gravida mi. Pellentesque et velit .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 6,
    img: "product1",
    name: "Смартфон Samsung Galaxy",
    price: "7 300 000",
    text: "Euismod faucibus turpis eu gravida mi. Pellentesque et velit aliquam .",
    discount: true,
    prize: true,
    refresh: false,
  },
  {
    id: 7,
    img: "product2",
    name: "Смартфон Apple iphone",
    price: "7 300 000",
    text: "Pellentesque et velit aliqua. Euismod faucibus turpis eu gravida mi .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 8,
    img: "product3",
    name: "Наушники Apple Airpods Pro",
    price: "7 300 000",
    text: "Gravida mi euismod faucibus turpis eu . Pellentesque et velit aliquam .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 9,
    img: "product4",
    name: "Samsung Galaxy Z Fold Plus",
    price: "7 300 000",
    text: "Aliquam euismod faucibus turpis eu gravida mi. Pellentesque et velit .",
    discount: true,
    prize: true,
    refresh: false,
  },
  {
    id: 10,
    img: "product5",
    name: "Смартфон Apple iphone",
    price: "7 300 000",
    text: "Aliquam euismod faucibus turpis eu gravida mi. Pellentesque et velit .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 11,
    img: "product5",
    name: "Смартфон Apple iphone",
    price: "7 300 000",
    text: "Aliquam euismod faucibus turpis eu gravida mi. Pellentesque et velit .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 12,
    img: "product4",
    name: "Samsung Galaxy Z Fold Plus",
    price: "7 300 000",
    text: "Aliquam euismod faucibus turpis eu gravida mi. Pellentesque et velit .",
    discount: true,
    prize: true,
    refresh: false,
  },
  {
    id: 13,
    img: "product3",
    name: "Наушники Apple Airpods Pro",
    price: "7 300 000",
    text: "Gravida mi euismod faucibus turpis eu . Pellentesque et velit aliquam .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 14,
    img: "product2",
    name: "Смартфон Apple iphone",
    price: "7 300 000",
    text: "Pellentesque et velit aliqua. Euismod faucibus turpis eu gravida mi .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 15,
    img: "product1",
    name: "Смартфон Samsung Galaxy",
    price: "7 300 000",
    text: "Euismod faucibus turpis eu gravida mi. Pellentesque et velit aliquam .",
    discount: true,
    prize: true,
    refresh: false,
  },
  {
    id: 16,
    img: "product5",
    name: "Смартфон Apple iphone",
    price: "7 300 000",
    text: "Aliquam euismod faucibus turpis eu gravida mi. Pellentesque et velit .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 17,
    img: "product4",
    name: "Samsung Galaxy Z Fold Plus",
    price: "7 300 000",
    text: "Aliquam euismod faucibus turpis eu gravida mi. Pellentesque et velit .",
    discount: true,
    prize: true,
    refresh: false,
  },
  {
    id: 18,
    img: "product3",
    name: "Наушники Apple Airpods Pro",
    price: "7 300 000",
    text: "Gravida mi euismod faucibus turpis eu . Pellentesque et velit aliquam .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 19,
    img: "product2",
    name: "Смартфон Apple iphone",
    price: "7 300 000",
    text: "Pellentesque et velit aliqua. Euismod faucibus turpis eu gravida mi .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 20,
    img: "product1",
    name: "Смартфон Samsung Galaxy",
    price: "7 300 000",
    text: "Euismod faucibus turpis eu gravida mi. Pellentesque et velit aliquam .",
    discount: true,
    prize: true,
    refresh: false,
  },
  {
    id: 21,
    img: "product1",
    name: "Смартфон Samsung Galaxy",
    price: "7 300 000",
    text: "Euismod faucibus turpis eu gravida mi. Pellentesque et velit aliquam .",
    discount: true,
    prize: true,
    refresh: false,
  },
  {
    id: 22,
    img: "product2",
    name: "Смартфон Apple iphone",
    price: "7 300 000",
    text: "Pellentesque et velit aliqua. Euismod faucibus turpis eu gravida mi .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 23,
    img: "product3",
    name: "Наушники Apple Airpods Pro",
    price: "7 300 000",
    text: "Gravida mi euismod faucibus turpis eu . Pellentesque et velit aliquam .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 24,
    img: "product4",
    name: "Samsung Galaxy Z Fold Plus",
    price: "7 300 000",
    text: "Aliquam euismod faucibus turpis eu gravida mi. Pellentesque et velit .",
    discount: true,
    prize: true,
    refresh: false,
  },
  {
    id: 25,
    img: "product5",
    name: "Смартфон Apple iphone",
    price: "7 300 000",
    text: "Aliquam euismod faucibus turpis eu gravida mi. Pellentesque et velit .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 26,
    img: "product1",
    name: "Смартфон Samsung Galaxy",
    price: "7 300 000",
    text: "Euismod faucibus turpis eu gravida mi. Pellentesque et velit aliquam .",
    discount: true,
    prize: true,
    refresh: false,
  },
  {
    id: 27,
    img: "product2",
    name: "Смартфон Apple iphone",
    price: "7 300 000",
    text: "Pellentesque et velit aliqua. Euismod faucibus turpis eu gravida mi .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 28,
    img: "product3",
    name: "Наушники Apple Airpods Pro",
    price: "7 300 000",
    text: "Gravida mi euismod faucibus turpis eu . Pellentesque et velit aliquam .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 29,
    img: "product4",
    name: "Samsung Galaxy Z Fold Plus",
    price: "7 300 000",
    text: "Aliquam euismod faucibus turpis eu gravida mi. Pellentesque et velit .",
    discount: true,
    prize: true,
    refresh: false,
  },
  {
    id: 30,
    img: "product5",
    name: "Смартфон Apple iphone",
    price: "7 300 000",
    text: "Aliquam euismod faucibus turpis eu gravida mi. Pellentesque et velit .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 31,
    img: "product5",
    name: "Смартфон Apple iphone",
    price: "7 300 000",
    text: "Aliquam euismod faucibus turpis eu gravida mi. Pellentesque et velit .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 32,
    img: "product4",
    name: "Samsung Galaxy Z Fold Plus",
    price: "7 300 000",
    text: "Aliquam euismod faucibus turpis eu gravida mi. Pellentesque et velit .",
    discount: true,
    prize: true,
    refresh: false,
  },
  {
    id: 33,
    img: "product3",
    name: "Наушники Apple Airpods Pro",
    price: "7 300 000",
    text: "Gravida mi euismod faucibus turpis eu . Pellentesque et velit aliquam .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 34,
    img: "product2",
    name: "Смартфон Apple iphone",
    price: "7 300 000",
    text: "Pellentesque et velit aliqua. Euismod faucibus turpis eu gravida mi .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 35,
    img: "product1",
    name: "Смартфон Samsung Galaxy",
    price: "7 300 000",
    text: "Euismod faucibus turpis eu gravida mi. Pellentesque et velit aliquam .",
    discount: true,
    prize: true,
    refresh: false,
  },
  {
    id: 36,
    img: "product5",
    name: "Смартфон Apple iphone",
    price: "7 300 000",
    text: "Aliquam euismod faucibus turpis eu gravida mi. Pellentesque et velit .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 37,
    img: "product4",
    name: "Samsung Galaxy Z Fold Plus",
    price: "7 300 000",
    text: "Aliquam euismod faucibus turpis eu gravida mi. Pellentesque et velit .",
    discount: true,
    prize: true,
    refresh: false,
  },
  {
    id: 38,
    img: "product3",
    name: "Наушники Apple Airpods Pro",
    price: "7 300 000",
    text: "Gravida mi euismod faucibus turpis eu . Pellentesque et velit aliquam .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 39,
    img: "product2",
    name: "Смартфон Apple iphone",
    price: "7 300 000",
    text: "Pellentesque et velit aliqua. Euismod faucibus turpis eu gravida mi .",
    discount: false,
    prize: false,
    refresh: true,
  },
  {
    id: 40,
    img: "product1",
    name: "Смартфон Samsung Galaxy",
    price: "7 300 000",
    text: "Euismod faucibus turpis eu gravida mi. Pellentesque et velit aliquam .",
    discount: true,
    prize: true,
    refresh: false,
  },
];
