import React from "react";
import Navbar from "./Navbar/Navbar";
import styles from "../styles/Layout.module.css";
import Sidebar from "./Sidebar/Sidebar";
import Head from "next/head";

interface Props {
  children: React.ReactNode;
}

export default function Layout({ children }: Props) {
  return (
    <div>
      <Head>
        <title>E-Commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo__icon.svg" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <div className={styles.main__sidebar}>
          <Sidebar />
        </div>
        <div className={styles.main__home}>{children}</div>
      </main>
    </div>
  );
}
